language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py36  
install: pip install tox coveralls
before_script: tox -e flake8
script: tox -e ${TOX_ENV}
after_success: coveralls
sudo: false
