language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.6
before_install: pip install --upgrade setuptools
install: pip install tox tox-travis coveralls
before_script: tox -e flake8
script: tox -r
after_success: coveralls
sudo: false
